# Generated by Django 4.1.7 on 2023-03-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0027_questionario_tipo_alter_boaspraticas_questao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='comentario',
            field=models.CharField(max_length=400),
        ),
    ]
